{
 "title": "Orderflow proxy (receiver)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "label_value",
    "label": "Instance",
    "query": {
     "query": "label_values({ job=\"orderflow-proxy\", aws_account = \"\"}, instance_name)"
    }
   },
   { "name": "label_name", "query": "instance_name" }
  ]
 },
 "panels": [
  { "title": "Public RPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(method) (rate(goutils_rpcserver_request_duration_milliseconds_count{$label_name=\"$label_value\", server_name=\"public_server\"}[1m]))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum(rate(goutils_rpcserver_request_duration_milliseconds_count{$label_name=\"$label_value\"}[1m]))",
     "legendFormat": "all methods"
    }
   ]
  },
  {
   "title": "Error Increase (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(method) (increase(goutils_rpcserver_error_count{$label_name=\"$label_value\", server_name=\"public_server\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Duration p = 0.9",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(method) (goutils_rpcserver_request_duration_milliseconds{$label_name=\"$label_value\", server_name=\"public_server\", quantile=\"0.9\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Duration p = 0.99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(method) (goutils_rpcserver_request_duration_milliseconds{$label_name=\"$label_value\", server_name=\"public_server\", quantile=\"0.99\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Per Second by peer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(peer) (rate(orderflow_proxy_api_incoming_requests_by_peer{$label_name=\"$label_value\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duplicate Requests Per Second by peer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by(peer) (rate(orderflow_proxy_api_duplicate_requests_by_peer{$label_name=\"$label_value\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Local RPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(method) (rate(goutils_rpcserver_request_duration_milliseconds_count{$label_name=\"$label_value\", server_name=\"local_server\"}[1m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Error Increase (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by(method) (increase(goutils_rpcserver_error_count{$label_name=\"$label_value\", server_name=\"local_server\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Duration p = 0.9",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by(method) (goutils_rpcserver_request_duration_milliseconds{$label_name=\"$label_value\", server_name=\"local_server\", quantile=\"0.9\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Duration p = 0.99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by(method) (goutils_rpcserver_request_duration_milliseconds{$label_name=\"$label_value\", server_name=\"local_server\", quantile=\"0.99\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate Limit Errors Increase (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "increase(orderflow_proxy_api_local_rate_limits{$label_name=\"$label_value\"}[1m])",
     "legendFormat": "local rate limits"
    }
   ]
  },
  { "title": "Orderflow sharing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  { "title": "Requests Per Second", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 } },
  { "title": "Error Increase (1m)", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 } },
  { "title": "Requests Duration p = 0.9", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 } },
  { "title": "Requests Duration p = 0.99", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 } },
  { "title": "Confighub", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Confighub Errors Increase (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum(orderflow_proxy_confighub_errors{$label_name=\"$label_value\"})",
     "legendFormat": "confighub errors"
    }
   ]
  },
  { "title": "Orderflow Archiving", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "increase(orderflow_proxy_archive_events_processed_total{$label_name=\"$label_value\"}[1m])",
     "legendFormat": "Events received"
    },
    {
     "expr": "increase(orderflow_proxy_archive_events_processed_err{$label_name=\"$label_value\"}[1m])",
     "legendFormat": "Events with errors"
    },
    {
     "expr": "increase(orderflow_proxy_archive_events_sent_ok{$label_name=\"$label_value\"}[1m])",
     "legendFormat": "Events sent successfully"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "sum(rate(orderflow_proxy_archive_rpc_duration_milliseconds_count{$label_name=\"$label_value\"}[1m]))",
     "legendFormat": "rpc: requests per second"
    }
   ]
  },
  {
   "title": "Error Increase (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "sum(increase(orderflow_proxy_archive_events_processed_err{$label_name=\"$label_value\"}[1m]))",
     "legendFormat": "rpc: errors"
    }
   ]
  },
  {
   "title": "Requests Duration p = 0.99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "sum(orderflow_proxy_archive_rpc_duration_milliseconds{$label_name=\"$label_value\", quantile=\"0.99\"})",
     "legendFormat": "rpc: request duration p=0.99"
    },
    {
     "expr": "sum(orderflow_proxy_archive_rpc_duration_milliseconds{$label_name=\"$label_value\", quantile=\"0.9\"})",
     "legendFormat": "rpc: request duration p=0.9"
    }
   ]
  }
 ]
}