{
 "title": "rbuilder",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "query": "rbuilder" },
   {
    "name": "instance_name",
    "query": {
     "query": "label_values(current_block{job=\"$job\"}, instance_name)"
    }
   },
   {
    "name": "github_repo_bidder",
    "query": "https://github.com/flashbots/rbuilder-internal"
   },
   {
    "name": "github_repo_rbuilder",
    "query": "https://github.com/flashbots/rbuilder-operator"
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Block",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "current_block{instance_name=\"$instance_name\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non 0 competition bids seen.",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "non_0_competition_bids{instance_name=\"$instance_name\", job=\"$job\"}",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Orderpool txs",
   "type": "stat",
   "description": "Pending transactions.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orderpool_txs{instance_name=\"$instance_name\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Simulation gas",
   "type": "stat",
   "description": "Gas spent simulating bundles on top of the block.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "MGas/Sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(simulation_gas_used{instance_name=\"$instance_name\", job=\"$job\"}[5m]) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orderpool bundles",
   "type": "stat",
   "description": "Pending bundles and share bundles.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orderpool_bundles{instance_name=\"$instance_name\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Simulation Thread Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(simulation_thread_work_time{instance_name=\"$instance_name\", job=\"$job\"}[5m]) / (rate(simulation_thread_work_time{instance_name=\"$instance_name\", job=\"$job\"}[5m]) + rate(simulation_thread_wait_time{instance_name=\"$instance_name\", job=\"$job\"}[5m]))",
     "legendFormat": "thread: {{worker_id}}"
    }
   ]
  },
  {
   "title": "Simulation OK orders",
   "type": "timeseries",
   "description": "Simulated orders on top of block as first step of block building.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Orders/Sec" } },
   "targets": [
    {
     "expr": "rate(simulated_ok_orders{instance_name=\"$instance_name\", job=\"$job\"}[5m])",
     "legendFormat": "Ok"
    },
    {
     "expr": "rate(simulated_failed_orders{instance_name=\"$instance_name\", job=\"$job\"}[5m])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Active Slots (10 min)",
   "type": "timeseries",
   "description": "Counts payloads when builder started jobs for block building. \n* There are 50 slots per 10 mins but we have to account for mev-boost adoption. \n* There are more than 1 payload job per slot when slot is suspected to be missed.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "increase(active_slots{job=\"$job\", instance_name=\"$instance_name\"}[10m])",
     "legendFormat": "10 min active slots"
    }
   ]
  },
  {
   "title": "Blocks API Errors",
   "type": "timeseries",
   "description": "Count of the errors returned from the flashbots/block-processor.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "increase(block_api_errors{job=\"$job\", instance_name=\"$instance_name\"}[1m])",
     "legendFormat": "{{relay}} - {{kind}}"
    }
   ]
  },
  {
   "title": "Blocks Simulation Errors",
   "type": "timeseries",
   "description": "* When submitting to the relay counts simulation errors returned by the relay (available only in non-optimistic mode).\n* When running in dry-run counts simulation errors received directly from the simulation node.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "increase(block_sim_errors{job=\"$job\", instance_name=\"$instance_name\"}[5m])",
     "legendFormat": "{{relay}} - {{kind}}"
    }
   ]
  },
  {
   "title": "Initiated relay submissions (10 min)",
   "type": "timeseries",
   "description": "Count of relay submissions that were initiated by the builder.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "increase(sum without (optimistic)(initiated_submissions{job=\"$job\", instance_name=\"$instance_name\"})[10m:])",
     "legendFormat": "total"
    },
    {
     "expr": "increase(initiated_submissions{job=\"$job\", instance_name=\"$instance_name\", optimistic=\"true\"}[10m])",
     "legendFormat": "optimistic"
    },
    {
     "expr": "increase(initiated_submissions{job=\"$job\", instance_name=\"$instance_name\", optimistic=\"false\"}[10m])",
     "legendFormat": "non-optimistic"
    }
   ]
  },
  {
   "title": "Relay Errors (10 min)",
   "type": "timeseries",
   "description": "Errors returned from the mev boost relay:\n* conn          - errors related to connection, e.g. tcp connection interruption.\n* too_many  - too many request error. rate limit of submissions was hit.\n* other         - unclassified errors.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "increase(relay_errors{job=\"$job\", instance_name=\"$instance_name\"}[10m])",
     "legendFormat": "{{relay}} - {{kind}}"
    }
   ]
  },
  {
   "title": "Relay Accepted Submissions (10 min)",
   "type": "timeseries",
   "description": "Counts submissions that were accepted by the relay.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "increase(relay_accepted_submissions{job=\"$job\", instance_name=\"$instance_name\"}[10m])",
     "legendFormat": "{{relay}}, optimistic: {{optimistic}}"
    }
   ]
  },
  {
   "title": "Min E2E included order latency inside builder (ms)",
   "type": "timeseries",
   "description": "For all blocks that are ready for submission to the relay its = minimum_{over included orders} (submission start - order received)\n\nThis metric still is kind of flawed:\n* if we have gaps in orderflow they go towards increasing this value \n* if some orders are slow to process we will not see them in the built block\n* merging builder does not take new orders into account as fast as possible\n\nbut its still captures the whole journey of the order through the builder including some places that we don't measure with \"fill time\" and \"finalize time\"",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, orders_in_last_built_block_e2e_lat_bucket{job=\"$job\", instance_name=\"$instance_name\"})",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.9, orders_in_last_built_block_e2e_lat_bucket{job=\"$job\", instance_name=\"$instance_name\"})",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.99, orders_in_last_built_block_e2e_lat_bucket{job=\"$job\", instance_name=\"$instance_name\"})",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Version History",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "version{job=\"$job\", instance_name=\"$instance_name\"} - 1",
     "legendFormat": "git {{git}}"
    }
   ]
  },
  {
   "title": "Bidding Service Version History",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "bidding_service_version{job=\"$job\", instance_name=\"$instance_name\"} - 1",
     "legendFormat": "git {{git}}"
    }
   ]
  },
  {
   "title": "Last Version",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "max(version{job=\"$job\", instance_name=\"$instance_name\"}) by (git, git_ref, build_time_utc)"
    }
   ]
  },
  {
   "title": "Last Bidding Service Version",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "max by(git, git_ref, build_time_utc) (bidding_service_version{job=\"$job\", instance_name=\"$instance_name\"})"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Fill Time (ms)",
   "type": "timeseries",
   "description": "Time spent filling block with transactions.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum without (builder_name)(block_fill_time_bucket{job=\"$job\", instance_name=\"$instance_name\"}))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.9,  sum without (builder_name)(block_fill_time_bucket{job=\"$job\", instance_name=\"$instance_name\"}))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.99,  sum without (builder_name)(block_fill_time_bucket{job=\"$job\", instance_name=\"$instance_name\"}))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Finalize Time (ms)",
   "type": "timeseries",
   "description": "Time spent finalizing blocks in milliseconds. Its mostly spent calculating state root hash of the block.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,  sum without (builder_name)(block_finalize_time_bucket{job=\"$job\", instance_name=\"$instance_name\"}))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.9,  sum without (builder_name)(block_finalize_time_bucket{job=\"$job\", instance_name=\"$instance_name\"}))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.99,  sum without (builder_name)(block_finalize_time_bucket{job=\"$job\", instance_name=\"$instance_name\"}))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Block built txs",
   "type": "timeseries",
   "description": "Number of txs in the built blocks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum without(builder_name) (block_built_txs_bucket{job=\"$job\", instance_name=\"$instance_name\"}))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.9, sum without(builder_name) (block_built_txs_bucket{job=\"$job\", instance_name=\"$instance_name\"}))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.99, sum without(builder_name) (block_built_txs_bucket{job=\"$job\", instance_name=\"$instance_name\"}))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Root Hash Time (ms)",
   "type": "timeseries",
   "description": "Time spent calculating root hash of the final block.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,  sum without (builder_name)(block_root_hash_time_bucket{job=\"$job\", instance_name=\"$instance_name\"}))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.9,  sum without (builder_name)(block_root_hash_time_bucket{job=\"$job\", instance_name=\"$instance_name\"}))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.99,  sum without (builder_name)(block_root_hash_time_bucket{job=\"$job\", instance_name=\"$instance_name\"}))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Block gas used",
   "type": "timeseries",
   "description": "Gas used in built blocks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum without(builder_name) (block_built_gas_used_bucket{job=\"$job\", instance_name=\"$instance_name\"}))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.9, sum without(builder_name) (block_built_gas_used_bucket{job=\"$job\", instance_name=\"$instance_name\"}))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.99, sum without(builder_name) (block_built_gas_used_bucket{job=\"$job\", instance_name=\"$instance_name\"}))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Block build sim MGas/s",
   "type": "timeseries",
   "description": "gas used in simulations (including failing bundles) / time spent building block",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum without(builder_name) (block_built_mgas_per_second_bucket{job=\"$job\", instance_name=\"$instance_name\"}))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.9, sum without(builder_name) (block_built_mgas_per_second_bucket{job=\"$job\", instance_name=\"$instance_name\"}))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.99, sum without(builder_name) (block_built_mgas_per_second_bucket{job=\"$job\", instance_name=\"$instance_name\"}))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Relay Submit Time (ms) [q = 0.5]",
   "type": "timeseries",
   "description": "Time between starting a bid request to the relay and getting a return. It counts time that relay spent validating block in non-optimistic mode. Usually it can be assumed that this is the time between initiating request and bid being available to the proposer.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, relay_submit_time_bucket{job=\"$job\", instance_name=\"$instance_name\"})",
     "legendFormat": "{{relay}} q=0.5"
    }
   ]
  },
  {
   "title": "Block built simulation gas used",
   "type": "timeseries",
   "description": "Gas used while building blocks. Includes gas used for failed bundles.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum without(builder_name) (block_built_sim_gas_used_bucket{job=\"$job\", instance_name=\"$instance_name\"}))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.9, sum without(builder_name) (block_built_sim_gas_used_bucket{job=\"$job\", instance_name=\"$instance_name\"}))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.99, sum without(builder_name) (block_built_sim_gas_used_bucket{job=\"$job\", instance_name=\"$instance_name\"}))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Validation Time (ms)",
   "type": "timeseries",
   "description": "Time spent validation block.\nBlock is validated:\n* if dry-run mode is on\n* if optimistic_prevalidate_optimistic_blocks = true and block is optimistic",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, block_validation_time_bucket{job=\"$job\", instance_name=\"$instance_name\"})",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.9, block_validation_time_bucket{job=\"$job\", instance_name=\"$instance_name\"})",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.99, block_validation_time_bucket{job=\"$job\", instance_name=\"$instance_name\"})",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Relay Submit Time (ms) [q = 0.9]",
   "type": "timeseries",
   "description": "Time between starting a bid request to the relay and getting a return. It counts time that relay spent validating block in non-optimistic mode. Usually it can be assumed that this is the time between initiating request and bid being available to the proposer.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, relay_submit_time_bucket{job=\"$job\", instance_name=\"$instance_name\"})",
     "legendFormat": "{{relay}} q=0.9"
    }
   ]
  },
  { "title": "Subsidy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Subsidized block count",
   "type": "timeseries",
   "description": "Count of blocks for which bid > true value",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "B/hr" } },
   "targets": [
    {
     "expr": "rate(subsidized_block_count{instance_name=\"$instance_name\", job=\"$job\"}[5m]) * 3600",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Subsidy value",
   "type": "timeseries",
   "description": "(bid -  true value) for blocks for which bid > true value",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, subsidy_value_bucket{job=\"$job\", instance_name=\"$instance_name\"})",
     "legendFormat": "{{kind}} .99"
    },
    {
     "expr": "histogram_quantile(0.95, subsidy_value_bucket{job=\"$job\", instance_name=\"$instance_name\"})",
     "legendFormat": "{{kind}} .95"
    },
    {
     "expr": "histogram_quantile(0.5, subsidy_value_bucket{job=\"$job\", instance_name=\"$instance_name\"})",
     "legendFormat": "{{kind}} .5"
    }
   ]
  },
  {
   "title": "Total spent ETH on subsidies per hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "ETH/hour" } },
   "targets": [
    {
     "expr": "rate(total_landed_subsidies_sum{instance_name=\"$instance_name\", job=\"$job\"}[5m]) * 3600",
     "legendFormat": "Ok"
    }
   ]
  }
 ]
}